Docs touchup
rtic-rs/cortex-m-rtic pull request #563
Opened 2021-12-19 00:37 UTC by AfoHT

Unleashed some language linters on the book

2021-12-19 05:54 UTC, korken89 requested changes
Started reviewing, not done yet

2021-12-19 05:54 UTC, korken89 commented on book/en/src/awesome_rtic.md
> +Pull-requests to this repo is welcome!
are welcome

2021-12-21 18:57 UTC, perlindgren approved these changes
Looks good, I made a few changes directly in the git web (never tried that before), let's see how it pans out. Besides these small changes, I think the docs are good to go.

2021-12-21 19:01 UTC, korken89 approved these changes

2021-12-21 19:02 UTC, korken89 commented
bors merge

2021-12-21 19:10 UTC, merged