README: Remove rustc badge and Requirements
rtic-rs/cortex-m-rtic pull request #569
Opened 2021-12-25 17:39 UTC by perlindgren

Remove rustc badge and requirements to edition 2018.

2021-12-25 17:44 UTC, AfoHT requested changes

2021-12-25 17:44 UTC, AfoHT commented on README.md
> +## [User documentation](https://rtic.rs)
```suggestion
## [User documentation](https://rtic.rs) - [(Development version)](https://rtic.rs/dev)
```
This is still relevant, RTIC didn't stop development :)

2021-12-25 18:52 UTC, AfoHT requested changes

2021-12-25 18:52 UTC, AfoHT commented on README.md
> +Documentation for the current master branch is found in [(Development version)](https://rtic.rs/dev).
```suggestion
Documentation for the [development version](https://rtic.rs/dev).
```
If separated to its own line then the parentheses doesn't make sense anymore :)

2021-12-26 09:15 UTC, korken89 approved these changes
bors merge

2021-12-26 09:23 UTC, merged